SCHEMA_VERSION="1"
VIOLENCE_TASK="violence_fighting"
VIOLENCE_LABEL="fighting"
MODEL_EXPERIMENT_ID="EXP-VIO-TEMPORAL-001"
MODEL_VERSION_LABEL="MODEL-VIO-BIGRU-ATTN-XD-V1"
MODEL_VERSION_ID="6d22f83d-17f8-5ecf-9f0f-246fa326ec72"
MODEL_CHECKPOINT_SHA256="1fa01d1be82ab3c63d33b4d5f1d5ef4ab2a176d1d2842afc842955ff72896772"
LIVE_THRESHOLD=0.906
LIVE_N_REQUIRED=3
LIVE_M_HISTORY=5
LIVE_STRIDE_FEATURE_STEPS=1
LIVE_WINDOW_FEATURE_STEPS=1
SCORE_SEMANTICS=("uncalibrated sigmoid score for the fighting positive class from "
                 "EXP-VIO-TEMPORAL-001; higher means more fighting-like")
ALLOWED_WORKER_ERROR_CODES=frozenset({"MODEL_LOAD_FAILED","UNSUPPORTED_INPUT","VIDEO_DECODE_FAILED","INFERENCE_FAILED","TRACKING_FAILED","INVALID_REQUEST","INSUFFICIENT_TEMPORAL_INPUT","INTERNAL_WORKER_ERROR"})
