from __future__ import annotations
from typing import Sequence
from alembic import op
import sqlalchemy as sa
revision="20260912_0001"; down_revision=None; branch_labels=None; depends_on=None
def upgrade()->None:
    op.create_table("cameras",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("name",sa.String(200),nullable=False),sa.Column("source_kind",sa.String(50),nullable=False),sa.Column("enabled",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.PrimaryKeyConstraint("id",name="pk_cameras"))
    op.create_table("models",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("name",sa.String(200),nullable=False),sa.Column("task_code",sa.String(100),nullable=False),sa.Column("source_name",sa.String(200),nullable=True),sa.Column("source_url",sa.Text(),nullable=True),sa.Column("license_name",sa.String(200),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.PrimaryKeyConstraint("id",name="pk_models"),sa.UniqueConstraint("name","task_code",name="uq_models_name_task"))
    op.create_table("model_versions",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("model_id",sa.Uuid(),nullable=False),sa.Column("version_label",sa.String(200),nullable=False),sa.Column("experiment_id",sa.String(200),nullable=True),sa.Column("artifact_reference",sa.Text(),nullable=False),sa.Column("artifact_sha256",sa.String(64),nullable=True),sa.Column("framework_name",sa.String(100),nullable=True),sa.Column("framework_version",sa.String(100),nullable=True),sa.Column("base_model_reference",sa.Text(),nullable=True),sa.Column("dataset_registry_id",sa.String(200),nullable=True),sa.Column("training_commit",sa.String(64),nullable=True),sa.Column("status_code",sa.String(50),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.ForeignKeyConstraint(["model_id"],["models.id"],name="fk_model_versions_model_id_models",ondelete="RESTRICT"),sa.PrimaryKeyConstraint("id",name="pk_model_versions"),sa.UniqueConstraint("model_id","version_label",name="uq_model_versions_model_label"))
    op.create_index("ix_model_versions_model_id","model_versions",["model_id"],unique=False)
    op.create_table("violence_event_policies",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("camera_id",sa.Uuid(),nullable=True),sa.Column("model_version_id",sa.Uuid(),nullable=False),sa.Column("enabled",sa.Boolean(),nullable=False),sa.Column("event_threshold_value",sa.Float(),nullable=False),sa.Column("score_semantics",sa.Text(),nullable=False),sa.Column("n_required",sa.Integer(),nullable=False),sa.Column("history_window_size",sa.Integer(),nullable=False),sa.Column("stride_feature_steps",sa.Integer(),nullable=False),sa.Column("cooldown_ms",sa.BigInteger(),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("event_threshold_value >= 0.0 AND event_threshold_value <= 1.0",name="ck_violence_event_policies_threshold_range"),sa.CheckConstraint("n_required > 0",name="ck_violence_event_policies_n_required_positive"),sa.CheckConstraint("history_window_size > 0",name="ck_violence_event_policies_history_positive"),sa.CheckConstraint("n_required <= history_window_size",name="ck_violence_event_policies_n_not_greater_than_m"),sa.CheckConstraint("stride_feature_steps > 0",name="ck_violence_event_policies_stride_positive"),sa.CheckConstraint("cooldown_ms IS NULL OR cooldown_ms >= 0",name="ck_violence_event_policies_cooldown_nonnegative"),sa.ForeignKeyConstraint(["camera_id"],["cameras.id"],name="fk_violence_event_policies_camera_id_cameras",ondelete="RESTRICT"),sa.ForeignKeyConstraint(["model_version_id"],["model_versions.id"],name="fk_violence_event_policies_model_version_id_model_versions",ondelete="RESTRICT"),sa.PrimaryKeyConstraint("id",name="pk_violence_event_policies"))
    op.create_index("ix_violence_event_policies_camera_id","violence_event_policies",["camera_id"],unique=False); op.create_index("ix_violence_event_policies_model_version_id","violence_event_policies",["model_version_id"],unique=False)
    op.create_table("events",sa.Column("id",sa.Uuid(),nullable=False),sa.Column("event_type_code",sa.String(100),nullable=False),sa.Column("camera_id",sa.Uuid(),nullable=False),sa.Column("rule_id",sa.Uuid(),nullable=True),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("severity_code",sa.String(50),nullable=True),sa.Column("requires_attention",sa.Boolean(),nullable=False),sa.Column("lifecycle_status_code",sa.String(50),nullable=True),sa.Column("correlation_id",sa.Uuid(),nullable=True),sa.Column("summary",sa.Text(),nullable=True),sa.ForeignKeyConstraint(["camera_id"],["cameras.id"],name="fk_events_camera_id_cameras",ondelete="RESTRICT"),sa.PrimaryKeyConstraint("id",name="pk_events"))
    op.create_index("ix_events_event_type_code","events",["event_type_code"],unique=False); op.create_index("ix_events_camera_id","events",["camera_id"],unique=False)
    op.create_table("violence_event_context",sa.Column("event_id",sa.Uuid(),nullable=False),sa.Column("model_version_id",sa.Uuid(),nullable=False),sa.Column("output_label",sa.String(100),nullable=False),sa.Column("score_value",sa.Float(),nullable=True),sa.Column("event_threshold_snapshot",sa.Float(),nullable=True),sa.Column("score_semantics",sa.Text(),nullable=True),sa.Column("window_started_at",sa.DateTime(timezone=True),nullable=True),sa.Column("window_ended_at",sa.DateTime(timezone=True),nullable=True),sa.Column("n_required_snapshot",sa.Integer(),nullable=True),sa.Column("history_window_size_snapshot",sa.Integer(),nullable=True),sa.Column("positive_count_snapshot",sa.Integer(),nullable=True),sa.CheckConstraint("score_value IS NULL OR (score_value >= 0.0 AND score_value <= 1.0)",name="ck_violence_event_context_score_range"),sa.CheckConstraint("event_threshold_snapshot IS NULL OR (event_threshold_snapshot >= 0.0 AND event_threshold_snapshot <= 1.0)",name="ck_violence_event_context_threshold_snapshot_range"),sa.ForeignKeyConstraint(["event_id"],["events.id"],name="fk_violence_event_context_event_id_events",ondelete="CASCADE"),sa.ForeignKeyConstraint(["model_version_id"],["model_versions.id"],name="fk_violence_event_context_model_version_id_model_versions",ondelete="RESTRICT"),sa.PrimaryKeyConstraint("event_id",name="pk_violence_event_context"))
    op.create_index("ix_violence_event_context_model_version_id","violence_event_context",["model_version_id"],unique=False)
def downgrade()->None:
    op.drop_index("ix_violence_event_context_model_version_id",table_name="violence_event_context"); op.drop_table("violence_event_context")
    op.drop_index("ix_events_camera_id",table_name="events"); op.drop_index("ix_events_event_type_code",table_name="events"); op.drop_table("events")
    op.drop_index("ix_violence_event_policies_model_version_id",table_name="violence_event_policies"); op.drop_index("ix_violence_event_policies_camera_id",table_name="violence_event_policies"); op.drop_table("violence_event_policies")
    op.drop_index("ix_model_versions_model_id",table_name="model_versions"); op.drop_table("model_versions"); op.drop_table("models"); op.drop_table("cameras")
